### ISSUE TITLE
[BUG] Fail falgs not working as expected

### ISSUE THREAD

**Issue by DarKDinDoN** [kaelad02/adv-reminder#1]
Hello,

FVTT 9.242
adv-reminder 0.2

Thx for this module. This is awesome.
I, like you, play with a little automation but not as much as Midi Qol.
This module really comes in handy. I was surprised to find this module working like a charm with BetterRolls5e.

When I set a `Fail` Midi Flag, only the saving throws are affected.
Actually, always the saving throws, never the skill throws or ability throws. (tested with & without BetterRolls5e)

EDIT: tested almost all Midi Qol Flags with BetterRolls5e. The only one not working is `CriticalReminder`.

**Comment by kaelad02** [comment]
Thanks for giving this a shot and glad to hear it works (mostly) with BetterRolls5e considering I hadn't tested with it.
You're right, only the fail flags for saving throws are implemented currently. I know Midi has fail flags for lots of checks but I didn't implement them because I didn't see any conditions or effects that would actually auto-fail them. I know Stunned will auto-fail Strength and Dexterity saving throws but I couldn't remember anything else auto-failing ability checks or any of the others. But if you want them, it's not too much work to add them.

**Comment by DarKDinDoN** [comment]
@kaelad02 no particular use-case here. Just thought it was a bug :)
