### ISSUE TITLE
[BUG] Suppressed effects with Midi Flags are still active

### ISSUE THREAD

**Issue by DarKDinDoN** [kaelad02/adv-reminder#2]
Hello,

FVTT 9.242
adv-reminder 0.2

When an active effect with Midi Qol Flags is `suppressed`, this module still applies the Midi Qol Flags effects.

To create a suppressed effect, just create an active effect on an item that grants effects on equip.
Then give this item to a PC or NPC & make sure the item is not equipped

**Comment by kaelad02** [comment]
Hmm, I thought I handled this by checking for the effect's `disabled` flag but maybe that's not working like I expected. I'll check this out.

**Comment by kaelad02** [comment]
I originally tested unavailable effects by creating an effect directly on an actor and enabling/disabling it manually. That's how I found out the effect's `data.disabled` field controlled it so that's what I used. I didn't try the AE on equipment use case. Looks like that is controlled by the effect's `isSuppressed` field so I can check for that as well.
