### ISSUE TITLE
[FEATURE] Consider supporting advantage with a condition

### ISSUE THREAD

**Issue by DarKDinDoN** [kaelad02/adv-reminder#3]
Hello,

Some items & features grant advantage, but only on certain conditions.

For example:  `Keen Smell. The tiger has advantage on Wisdom (Perception) checks that rely on smell.`

Maybe this module can implement some kind of reminder about that?
Since we can't automate this, possibly a simple chat message? Or a message before rolling?

**Comment by DarKDinDoN** [comment]
@kaelad02 After more thoughts, I think it could be an override of the roll window.
Like adding a text in this window: xxxxxxxxxxxxx (advantage)

**Comment by kaelad02** [comment]
Some text above the buttons, yeah, same. If I did this, that's what I was thinking. Still nervous about doing it though. Originally thought it would just be this helper and was hoping not to override roll dialogs. Still worth considering though.

![image](https://user-images.githubusercontent.com/19502084/149683269-d0e1d978-1d05-4121-95aa-63bb94f9f9f1.png)

**Comment by DarKDinDoN** [comment]
@kaelad02 Yes, that would be great.
I understand that can be challenging. But, oh man, that would be great! 😸

**Comment by kaelad02** [comment]
Doesn't look as hard as I feared. I was afraid I'd have to override the item's entire `rollAttack` method, for example, but I might be able to create a roll dialog template to include an extra message. Still investigating

**Comment by kaelad02** [comment]
I know we've been discussing this on your PR as well, but I figured we should use the issue to figure out the details about what we want this feature to be.

### Conditional Advantage vs. Message

When initially proposed, we were thinking these were reminders for conditional advantage or disadvantage (e.g. Keen Smell or Pack Tactics). That would drive the design towards using active effect keys that include `advantage` or `disadvantage` in them so the module could include those words as a prefix for the message. For example, Keen Smell's active effect could be something like `flags.midi-qol.advantage.skill.prc.message = "when relying on smell"`. When that actor rolls a Perception Skill Check, then we'd include a message above the buttons like `Advantage: when relying on smell`. I think we can expand this.

I think we should treat these as additional messages for the roll dialog and not tie them to advantage, disadvantage, or critical rolls. I can think of use cases for damage rolls wanting a message reminding the player to include extra damage (e.g. Sneak Attack or Divine Fury). Instead, the active effect would look something like `flags.adv-reminder.message.damage = "Sneak Attack: 2d6" `. Then we'd include a message on a damage roll that says exactly `Sneak Attack: +2d6`. Then if the player wants to add the extra damage they could just copy/paste that into the Situational Bonus field.

### Active Effect Keys

Midi QOL defines active effect keys to trigger advantage, disadvantage, and critical rolls. I think we should use those keys as a template for this feature. For example, `flags.midi-qol.advantage.attack.all` and `flags.midi-qol.disadvantage.attack.all` set advantage/disadvantage respectively for all attack rolls. If we want a message to appear in the roll dialog on all attack rolls, we would use `flags.adv-reminder.message.attack.all`.

- Replace `midi-qol` with `adv-reminder`. Since this module is defining the key/flag, we should probably put it in our module's "namespace"
- Replace `advantage` or `disadvantage` with `message`
- Keep the part after the same to define when the message shows up

That scheme for the keys should allow us to put a message anywhere we would normally add advantage or disadvantage.

### Damage Roll Keys

That pattern works for all the d20 rolls where advantage and disadvantage apply, even death saves. It doesn't work for damage rolls. The critical/normal keys for damage rolls are a bit different: `flags.midi-qol.critical.all` for a crit and `flags.midi-qol.noCritical.all` for normal damage. Since it's keying off a damage roll, I think we can use that word as part of the key making it `flags.adv-reminder.message.damage.all`. This seems to follow what Midi QOL does with optional bonus effects, using `flags.midi-qol.optional.Name.damage` for a "bonus to apply to damage done."

### Active Effect Values

Since the message keys are defined for the roll type (e.g. attack roll, saving throw) and not specifically for advantage, the module would use the value as-is. We should also support inclusion of any HTML tags (e.g. may want to bold some text).

### Examples

Keen Smell
> `flags.adv-reminder.message.skill.prc | Custom | <b>Advantage:</b> when relying on smell`

Pack Tactics
> `flags.adv-reminder.message.attack.all | Custom | <b>Pack Tactics:</b> You have advantage on an attack roll against a creature if at least one of your allies is within 5 feet of the creature and the ally isn’t incapacitated.`

Sneak Attack
> `flags.adv-reminder.message.damage.all | Custom | <b>Sneak Attack:</b> +2d6`


### Open questions

1. Attack and damage rolls can have a target. It's useful when the target is granting advantage or hits are automatically crits. Should we define `grants.message` keys that show up on attack and damage rolls when they're targeted? I can't think of a use case, but maybe it's worth doing.

**Comment by DarKDinDoN** [comment]
Thx for this great recap. Very well written.
Agreed on all!

Just adding what I wrote on the PR and that is not mentioned in your recap:
- The way you are handling the hooking was what I did at first. It works until multiple roll dialogs are shown at the same time. The problem is due to the render time of the roll dialog. If you initiate the render of a dialog and initiate a second, the order of rendering is not guarantee and not sequential. Thus ending up with messages in the wrong roll dialog. You can take a look at how I handled that. (i.e: multiple players making a save roll at the same time, or multiple roll dialogs opened by the same player at once with smt like "Token HUD actions" )
- Display more than one message
- Just a touch of styling would be pleasant. Default font size is too big. Not much you can write in a single line.

Overall, I feel it's turning to be a great feature! 😸 

Would you mind merging this as well? cf5f783
It's just a compatibility fix for MRE (https://github.com/ElfFriend-DnD/FVTT-Minimal-Rolling-Enhancements-DND5E). MRE, like this module, is low automation oriented. It just fast-forwards rolls. This change is to catch the MRE fast-forwards (with a fastForward property added by MRE in the options object)
