### ISSUE TITLE
Feature Request: Source Information

### ISSUE THREAD

**Issue by webmaster94** [kaelad02/adv-reminder#30]
Hello, I have just started using this module as I always have Midi-QOL set to not fast forward rolls in case of specific changes needed. I use Convenient Effects to handle features/spells and also use custom dynamic active effects for custom created features or items. It is nice that the reminder is there, though the messages feature seems a bit clunky. For one, it would require me to update all of the my effects that are already there to have the message. Is it possible to add a setting to have source information before the reminder. 

Currently this is what Guiding Bolt looks like when a creature is targeted: 
![image](https://user-images.githubusercontent.com/85364225/185787467-61792f81-a902-45b6-9fe1-7e5eeedb08f0.png)

Is it possible to get the effects name so that the message could automatically look like this:
![image](https://user-images.githubusercontent.com/85364225/185788079-a7e3d973-d965-4340-978d-5c09c5028c6a.png)

**Comment by kaelad02** [comment]
Those messages are actually coming from Midi QOL itself. By that, I mean that Midi is generating the messages, Advantage Reminder is just showing them. It was an integration attempt to use this module to show the source of advantage/disadvantage. You can see some early discussions about it in #16.

You're right, it doesn't really show the source and currently only works on attack rolls, nothing else. If you want to improve it, I suggest filing an issue w/ Midi to finish the feature.

**Comment by webmaster94** [comment]
I know that the message: grants.attack.all is coming from midi as that is the flag but you are saying that when your module grabs the flag for display, it can't also get the effect name that the flag originates from? I looked through the issue that you linked and I see that tposney can get Midi to send the info but I figured that Advantage Reminders would be able to get it itself, but they may not be possible. 

The main reason I was asking is because all of the other pre-populated content focuses on Midi-QOL and DAE so trying to get this module to work takes a lot of extra input on the part of all of the GMs.

**Comment by kaelad02** [comment]
That would require me to write the same feature as Midi. When AR goes through the effects that grant advantage/disadvantage, it would save the name of the effect so it could be added as a message. The one advantage (pardon the pun) to having AR do it instead of Midi is that AR goes through the active effects on the actor where I can easily grab the effect's name. Midi applies those flags to the actor and checks the actor data so there's no effect name for it to include.

So that's one argument for AR doing this instead of Midi: it's got a better chance knowing the source. The one downside is some implementation details, especially in the future. In the upcoming v10 compatible release of the dnd5e system, it's introducing some new hooks that I would like to use. One benefit is that it makes it a lot easier to stop processing advantage/disadvantage if you're already using Midi since it's already doing that. Adding this feature would make that a bit more complex, but I can probably do it without the code being too hacky.

I had thought about this kind of feature before, but way early before the messages feature existed. But now that it's here, it makes displaying the source easier. I'm still not 100% sure I'll add it, but it's strongly worth considering.
