### ISSUE TITLE
damage roll evaluation is broken on 4.0.0

### ISSUE THREAD

**Issue by etiquettestartshere** [kaelad02/adv-reminder#76]
![image](https://github.com/user-attachments/assets/02226970-07db-4875-9354-7d42bcd510bd)

**Comment by etiquettestartshere** [comment]
Advantage Reminder version 4.0.2, dnd5e version 4.0.0, foundry 12.331

chat card on the left is with no modules, chat card on the right is advantage reminder (sorry, i thought the expected results were clear from the screenshot, but basically the str value, in this case -1, and the magical bonus, in this case +1, are not correctly applied to the roll.
![image](https://github.com/user-attachments/assets/b759d6ef-ebee-49fc-8d99-7859a5cf35a8)![image](https://github.com/user-attachments/assets/d97b97ca-bbac-4008-b082-3abbbca984e1)

further info, the item used in the test is the SRD 5.1 Maul +1, used both completely default and also with 2d6 manually written as the formula (found this while helping someone on discord troubleshoot, is the reason for that). There are no errors in console, only deprecation warnings

**Comment by kaelad02** [comment]
Very unexpected since AR doesn't touch the damage parts or roll data. I'll take a look

**Comment by kaelad02** [comment]
It looks like a bug with the dnd5e system itself. I ran a test where I started to comment out code that AR uses during damage rolls, in the `dnd5e.preRollDamage` hook and I could still reproduce the issue. Then I tested with no modules and ran this macro before making a damage roll and I was able to reproduce the issue:
```js
Hooks.once("dnd5e.preRollDamage", console.log);
```
I don't think dnd5e's 4.0.1 update fixed it since there isn't any code change around that hook. I'll test it on 4.0.1 and see if it happens there, and if so, create an issue w/ them.

**Comment by kaelad02** [comment]
Confirmed that it is a system bug and reported it there: foundryvtt/dnd5e#4285. I'm putting the finishing touches on a v4.0-compatible release and plan on finishing that up in the next day. It will fix this issue since the new version doesn't use that hook but a new one that'll avoid the issue altogether. I have confirmed that in the code I'm working on.
